### ISSUE TITLE
Feature Request: Save the IP values somewhere

### ISSUE THREAD

**Issue by maxwellmb** [scexao-org/vampires_dpp#10]
It can be useful to have the IP values saved somewhere.

**Comment by mileslucas** [comment]
I've got this in the works:

https://github.com/scexao-org/vampires_dpp/blob/ml/mm/src/vampires_dpp/pipeline/pipeline.py#L402:403

**Comment by mileslucas** [comment]
live with v0.7.1 d59d437eced2b178d239a053ab36f426d45b5199
