### ISSUE TITLE
Exists if FITS file EM gain value of zero

### ISSUE THREAD

**Issue by mwanakijiji** [scexao-org/vampires_dpp#13]
The pipeline doesn't like a EM gain value of zero (in the FITS headers in question, U_EMGAIN=0.):

```
  File "/Users/bandari/anaconda3/envs/betel_env/lib/python3.10/site-packages/vampires_dpp/constants.py", line 49, in effgain
    return self.gain / self.emgain
ZeroDivisionError: float division by zero
```

Can returned value be assigned one which allows the rest of the pipeline to continue?

**Comment by mileslucas** [comment]
Thanks for the bug report! I had only tested this on data with EM gain so never saw it, a good reminder to work on testing.

Fixed with https://github.com/scexao-org/vampires_dpp/commit/2855eb363d49cd787606fa001a9f1af9f58f4a39
