### ISSUE TITLE
Not providing frame_centers crashes 

### ISSUE THREAD

**Issue by maxwellmb** [scexao-org/vampires_dpp#2]
The tutorial claims that if you don't provide frame_centers in the calibration file then it'll just pick the middle of the frame, but this doesn't currently work (and there's no evidence in the code that this feature has been implemented).

**Comment by mileslucas** [comment]
Thanks for the bug report, will investigate.

**Comment by mileslucas** [comment]
Should be fixed with https://github.com/scexao-org/vampires_dpp/commit/083504204af80a33f44fa27ee05ef04552bcaac5
